### ISSUE TITLE
CI: GitHub Actions for maintenance branches

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#12493]
The `.github/workflows/testing.yml` file is present in the `maintenance/1.5.x` branch, but there is apparently no MacOS testing happening for PRs to that branch.

This is presumably because of the header block branch targeting:

```yml
name: macOS tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
```

I imagine it would not be too hard to produce a patch to `master` branch that is suitable for a backport and allows running on the maintenance series of branches.
