### ISSUE TITLE
cibuildwheel GitHub Action creates a lot of spurious notifications

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#16970]
This is for regular opening of a PR, and I think it also happens when adding a label to a PR for example:

<img width="416" alt="image" src="https://user-images.githubusercontent.com/98330/188610957-db769c9d-c6b7-4fa0-92b9-bc992d7ce6b6.png">

The trigger conditions are unusual:
```yaml
on:
  schedule:
  #        ┌───────────── minute (0 - 59)
  #        │  ┌───────────── hour (0 - 23)
  #        │  │ ┌───────────── day of the month (1 - 31)
  #        │  │ │ ┌───────────── month (1 - 12 or JAN-DEC)
  #        │  │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
  #        │  │ │ │ │
  - cron: "9  9 * * 6"
  # push:
  pull_request:
      types: [labeled, opened, synchronize, reopened]
  workflow_dispatch:
```

It may be those conditions, or it may be the `needs: get_commit_message` condition of `build_wheels`, which is also unique.

Cc @andyfaff, @lithomas1 in case one of you has already looked at this. scikit-learn has an alternative method: https://github.com/scikit-learn/scikit-learn/blob/main/.github/workflows/wheels.yml#L37. @thomasjpfan are you happy with how that functions?
