### ISSUE TITLE
CI: Meson Python 3.11 MacOS job is failing

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#18218]
```
meson.build:1:0: ERROR: Cython compiler 'cython' cannot compile programs
```

In unrelated PRs like:
- https://github.com/scipy/scipy/pull/18216
- https://github.com/scipy/scipy/pull/18217

Comparing recent success vs. failure log:
- failure is Python `3.11.1` vs. `3.11.0` in success (conda)
- failure gains dependency `libexpat` (conda)
- `clang` versions look identical in the meson config stage
- cython and meson versions look identical
- `python_abi                                   3.10-3_cp310 --> 3.11-3_cp311  ` (conda) updates
in failed version of log but no such update in the successful version

Not sure if any of that is suspicious...

**Comment by rgommers** [comment]
It is failing/passing inconsistently on `main`. It may be a caching issue. On the last job that passed ([CI log](https://github.com/scipy/scipy/actions/runs/4573080117/jobs/8073074429)), it looks like this:

![image](https://user-images.githubusercontent.com/98330/229100460-14cc6701-0a3c-49a1-a13b-f24abbcfb5a1.png)

On the last job that failed ([CI log](https://github.com/scipy/scipy/actions/runs/4573866968/jobs/8074817775)), it looks like:

![image](https://user-images.githubusercontent.com/98330/229100658-ddb22674-fac9-4ba9-a61c-2064b081ad91.png)

At that point, the "build and install SciPy" job step has `conda` complaining on activation about an inconsistent environment after retrieving new channel metadata in that test step:

<details>

```
Run conda activate scipy-dev
  conda activate scipy-dev
  
  # optional test dependencies
  conda install scikit-umfpack scikit-sparse
  
  # Python.org installers still use 10.9, so let's use that too. Note
  # that scikit-learn already changed to 10.13 in Jan 2021, so increasing
  # this number in the future (if needed) should not be a problem.
  # Conda-forge is still at 10.9, see:
  # https://conda-forge.org/docs/maintainer/knowledge_base.html#requiring-newer-macos-sdks
  export MACOSX_DEPLOYMENT_TARGET=10.9
  export MACOSX_SDK_VERSION=10.9
  CC="ccache $CC" python dev.py build -j 2
  shell: /bin/bash -l {0}
  env:
    INSTALLDIR: build-install
    CCACHE_DIR: /Users/runner/work/scipy/scipy/.ccache
    INPUT_RUN_POST: true
    CONDA: /Users/runner/miniconda3
    CONDA_PKGS_DIR: /Users/runner/conda_pkgs_dir
Collecting package metadata (current_repodata.json): ...working... done

The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - conda-forge/noarch::urllib3==1.26.15=pyhd8ed1ab_0
  - conda-forge/osx-64::markupsafe==2.1.2=py310h90acd4f_0
  - conda-forge/noarch::requests==2.28.2=pyhd8ed1ab_0
  - conda-forge/osx-64::psutil==5.9.4=py310h90acd4f_0
  - conda-forge/osx-64::pybind11==2.10.4=py310ha23aa8a_0
  - conda-forge/osx-64::tornado==6.2=py310h90acd4f_1
  - conda-forge/noarch::sphinx-design==0.3.0=pyhd8ed1ab_0
  - conda-forge/osx-64::cffi==1.15.1=py310ha78151a_3
  - conda-forge/noarch::pyopenssl==23.1.1=pyhd8ed1ab_0
  - conda-forge/osx-64::scipy==1.10.1=py310h240c617_0
  - conda-forge/noarch::jinja2==3.1.2=pyhd8ed1ab_1
  - conda-forge/osx-64::scikit-sparse==0.4.8=py310h01013de_1
  - conda-forge/noarch::pytest-cov==4.0.0=pyhd8ed1ab_0
  - conda-forge/osx-64::asv==0.4.2=py310hba3363e_3
  - conda-forge/osx-64::contourpy==1.0.7=py310ha23aa8a_0
  - conda-forge/noarch::cython-lint==0.14.0=pyhd8ed1ab_0
  - conda-forge/osx-64::matplotlib-base==3.7.1=py310he725631_0
  - conda-forge/noarch::sphinx==5.3.0=pyhd8ed1ab_0
  - conda-forge/osx-64::python_abi==3.10=3_cp310
  - conda-forge/osx-64::fonttools==4.39.3=py310h90acd4f_0
  - conda-forge/osx-64::numpy==1.24.2=py310h788a5b3_0
  - conda-forge/osx-64::brotlipy==0.7.0=py310h90acd4f_1005
  - conda-forge/osx-64::kiwisolver==1.4.4=py310ha23aa8a_1
  - conda-forge/noarch::numpydoc==1.5.0=pyhd8ed1ab_0
  - conda-forge/osx-64::ruff==0.0.260=py310h1e0b698_0
  - conda-forge/osx-64::pillow==9.4.0=py310h6b2f720_2
  - conda-forge/osx-64::matplotlib==3.7.1=py310h2ec42d9_0
  - conda-forge/osx-64::cryptography==40.0.1=py310hdd0c95c_0
  - conda-forge/noarch::pooch==1.7.0=pyha770c72_3
  - conda-forge/osx-64::pythran==0.12.1=py310h3e792ce_0
  - conda-forge/osx-64::scikit-umfpack==0.3.3=py310hbb64599_1
  - conda-forge/osx-64::coverage==7.2.2=py310h90acd4f_0
  - conda-forge/osx-64::gmpy2==2.1.2=py310hb691cb2_1
  - conda-forge/noarch::pydata-sphinx-theme==0.9.0=pyhd8ed1ab_1
  - conda-forge/osx-64::pybind11-global==2.10.4=py310ha23aa8a_0
  - conda-forge/osx-64::mypy==1.1.1=py310h90acd4f_0
  - conda-forge/osx-64::docutils==0.19=py310h2ec42d9_1
  - conda-forge/osx-64::unicodedata2==15.0.0=py310h90acd4f_0
  - conda-forge/osx-64::cython==0.29.33=py310h7a76584_0
Solving environment: ...working... done
```

</details>

So the environment is updated when there is no cache hit, and that pulls in a new `cython` package or something else that's problematic: 

```yaml
    - name: Update Conda Environment
      run: mamba env update -n scipy-dev -f environment.yml
      if: steps.envcache.outputs.cache-hit != 'true'

    - name: Build and Install SciPy
      shell: bash -l {0}
      run: |
        conda activate scipy-dev

        # optional test dependencies
        conda install scikit-umfpack scikit-sparse
```
