### ISSUE TITLE
DOC: Titles of long function names in API Reference truncated and horizontal scroll bar in code examples in 3 column layout

### ISSUE THREAD

**Issue by DietBru** [scipy/scipy#20635]
As shown in the bottom portion of the screenshot below, the HTML documentation does not use the full window width of the browser. For some titles, the default width is not enough (red square in screenshot). Adding the following lines to the file `doc/source/_static/scipy.css`

```css

.bd-main .bd-content .bd-article-container {
  max-width: 100%;  /* default is 60em */
}
.bd-page-width {
  max-width: 100%;  /* default is 88rem */
}
```

lets the center column use the full width (top portion of screenshot). Details can be found in the [pydata-sphinx-theme docs](https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/layout.html#horizontal-spacing).
![image](https://github.com/scipy/scipy/assets/12721170/3b551bd4-e04e-4ff1-9f2b-1b22907b863f)
