### ISSUE TITLE
median_filter accepts float origin, but minimum_filter and maximum_filter don't

### ISSUE THREAD

**Issue by jakirkham** [scipy/scipy#7343]
There seems to be some discrepancies between what the `median_filter` accepts for the `origin` argument and what the `minimum_filter` and `maximum_filter` accept. Appears the `median_filter` will take a `float` for `origin` and effectively runs [`numpy.fix`]( https://docs.scipy.org/doc/numpy/reference/generated/numpy.fix.html ) on it to get a reasonable integer value. However, the `minimum_filter` and `maximum_filter` simply error out if given a `float` value for `origin`. Example with test environment details below.

Code snippet:

<details>

```python
In [1]: import numpy

In [2]: import numpy as np

In [3]: import scipy

In [4]: import scipy as sp

In [5]: import scipy.ndimage

In [6]: import scipy.ndimage.filters

In [7]: import scipy.ndimage.filters as sp_ndf

In [8]: np.set_printoptions(linewidth=157)

In [9]: a = np.arange(140.0).reshape(10, 14)

In [10]: sp_ndf.minimum_filter(a, 5, origin=2.1)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-10-adc2bf1a8e1e> in <module>()
----> 1 sp_ndf.minimum_filter(a, 5, origin=2.1)

/zopt/conda2/envs/test/lib/python2.7/site-packages/scipy/ndimage/filters.pyc in minimum_filter(input, size, footprint, output, mode, cval, origin)
   1112     """
   1113     return _min_or_max_filter(input, size, footprint, None, output, mode,
-> 1114                               cval, origin, 1)
   1115 
   1116 

/zopt/conda2/envs/test/lib/python2.7/site-packages/scipy/ndimage/filters.pyc in _min_or_max_filter(input, size, footprint, structure, output, mode, cval, origin, minimum)
   1054         if len(axes) > 0:
   1055             for axis, size, origin, mode in axes:
-> 1056                 filter_(input, int(size), axis, output, mode, cval, origin)
   1057                 input = output
   1058         else:

/zopt/conda2/envs/test/lib/python2.7/site-packages/scipy/ndimage/filters.pyc in minimum_filter1d(input, size, axis, output, mode, cval, origin)
    955     mode = _ni_support._extend_mode_to_code(mode)
    956     _nd_image.min_or_max_filter1d(input, size, axis, output, mode, cval,
--> 957                                   origin, 1)
    958     return return_value
    959 

TypeError: integer argument expected, got float

In [11]: sp_ndf.maximum_filter(a, 5, origin=2.1)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-11-79b884f24b25> in <module>()
----> 1 sp_ndf.maximum_filter(a, 5, origin=2.1)

/zopt/conda2/envs/test/lib/python2.7/site-packages/scipy/ndimage/filters.pyc in maximum_filter(input, size, footprint, output, mode, cval, origin)
   1149     """
   1150     return _min_or_max_filter(input, size, footprint, None, output, mode,
-> 1151                               cval, origin, 0)
   1152 
   1153 

/zopt/conda2/envs/test/lib/python2.7/site-packages/scipy/ndimage/filters.pyc in _min_or_max_filter(input, size, footprint, structure, output, mode, cval, origin, minimum)
   1054         if len(axes) > 0:
   1055             for axis, size, origin, mode in axes:
-> 1056                 filter_(input, int(size), axis, output, mode, cval, origin)
   1057                 input = output
   1058         else:

/zopt/conda2/envs/test/lib/python2.7/site-packages/scipy/ndimage/filters.pyc in maximum_filter1d(input, size, axis, output, mode, cval, origin)
   1007     mode = _ni_support._extend_mode_to_code(mode)
   1008     _nd_image.min_or_max_filter1d(input, size, axis, output, mode, cval,
-> 1009                                   origin, 0)
   1010     return return_value
   1011 

TypeError: integer argument expected, got float

In [12]: sp_ndf.median_filter(a, 5, origin=2.1)
Out[12]: 
array([[  15.,   15.,   15.,   15.,   16.,   17.,   18.,   19.,   20.,   21.,   22.,   23.,   24.,   25.],
       [  14.,   14.,   14.,   14.,   15.,   16.,   17.,   18.,   19.,   20.,   21.,   22.,   23.,   24.],
       [  14.,   14.,   14.,   14.,   15.,   16.,   17.,   18.,   19.,   20.,   21.,   22.,   23.,   24.],
       [  15.,   15.,   15.,   15.,   16.,   17.,   18.,   19.,   20.,   21.,   22.,   23.,   24.,   25.],
       [  29.,   29.,   29.,   29.,   30.,   31.,   32.,   33.,   34.,   35.,   36.,   37.,   38.,   39.],
       [  43.,   43.,   43.,   43.,   44.,   45.,   46.,   47.,   48.,   49.,   50.,   51.,   52.,   53.],
       [  57.,   57.,   57.,   57.,   58.,   59.,   60.,   61.,   62.,   63.,   64.,   65.,   66.,   67.],
       [  71.,   71.,   71.,   71.,   72.,   73.,   74.,   75.,   76.,   77.,   78.,   79.,   80.,   81.],
       [  85.,   85.,   85.,   85.,   86.,   87.,   88.,   89.,   90.,   91.,   92.,   93.,   94.,   95.],
       [  99.,   99.,   99.,   99.,  100.,  101.,  102.,  103.,  104.,  105.,  106.,  107.,  108.,  109.]])
```

</details>

<br>

conda environment details ([docs]( https://conda.io/docs/using/envs.html#use-environment-from-file )):

<details>

```yaml
# environment.yml
name: test
channels: !!python/tuple
- !!python/unicode
  'conda-forge'
- !!python/unicode
  'defaults'
dependencies:
- conda-forge::appnope=0.1.0=py27_0
- conda-forge::backports.shutil_get_terminal_size=1.0.0=py27_1
- conda-forge::blas=1.1=openblas
- conda-forge::ca-certificates=2017.1.23=1
- conda-forge::certifi=2017.4.17=py27_0
- conda-forge::decorator=4.0.11=py27_0
- conda-forge::enum34=1.1.6=py27_1
- conda-forge::ipython=5.3.0=py27_0
- conda-forge::ipython_genutils=0.2.0=py27_0
- conda-forge::libgfortran=3.0.0=0
- conda-forge::ncurses=5.9=10
- conda-forge::numpy=1.12.1=py27_blas_openblas_200
- conda-forge::openblas=0.2.19=2
- conda-forge::openssl=1.0.2k=0
- conda-forge::pathlib2=2.2.1=py27_0
- conda-forge::pexpect=4.2.1=py27_0
- conda-forge::pickleshare=0.7.3=py27_0
- conda-forge::prompt_toolkit=1.0.14=py27_0
- conda-forge::ptyprocess=0.5.1=py27_0
- conda-forge::pygments=2.2.0=py27_0
- conda-forge::python=2.7.13=0
- conda-forge::readline=6.2=0
- conda-forge::scandir=1.5=py27_1
- conda-forge::scipy=0.19.0=np112py27_blas_openblas_200
- conda-forge::setuptools=33.1.1=py27_0
- conda-forge::simplegeneric=0.8.1=py27_0
- conda-forge::six=1.10.0=py27_1
- conda-forge::sqlite=3.13.0=1
- conda-forge::tk=8.5.19=1
- conda-forge::traitlets=4.3.2=py27_0
- conda-forge::wcwidth=0.1.7=py27_0
- conda-forge::zlib=1.2.11=0
```
</details>
